"""empty message

Revision ID: 1227092d636a
Revises: ae346256b650
Create Date: 2019-12-02 19:23:15.898717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1227092d636a'
down_revision = 'ae346256b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('image', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('season', sa.String(length=140), nullable=True),
    sa.Column('year', sa.String(length=140), nullable=True),
    sa.Column('num_episodes', sa.String(length=140), nullable=True),
    sa.Column('esrb', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('character',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('image', sa.String(length=140), nullable=True),
    sa.Column('anime_name', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['anime_name'], ['anime.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    op.drop_table('anime')
    # ### end Alembic commands ###
