"""empty message

Revision ID: 590b2cffea78
Revises: 1227092d636a
Create Date: 2019-12-02 19:41:50.690526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590b2cffea78'
down_revision = '1227092d636a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waifu',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('image', sa.String(length=140), nullable=True),
    sa.Column('anime_name', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['anime_name'], ['anime.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('name', sa.VARCHAR(length=140), nullable=False),
    sa.Column('description', sa.VARCHAR(length=140), nullable=True),
    sa.Column('image', sa.VARCHAR(length=140), nullable=True),
    sa.Column('anime_name', sa.VARCHAR(length=140), nullable=True),
    sa.ForeignKeyConstraint(['anime_name'], ['anime.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_table('waifu')
    # ### end Alembic commands ###
